
-- create
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY ,
 pro_p  float
);

-- insert
INSERT INTO EMPLOYEE VALUES ('1', '10.00');
INSERT INTO EMPLOYEE VALUES ('2', '15.50');
INSERT INTO EMPLOYEE VALUES ('3', '8.75');
INSERT INTO EMPLOYEE VALUES ('4', '20.25');
INSERT INTO EMPLOYEE VALUES ('5', '12.00');

-- fetch 
SELECT * FROM EMPLOYEE ;


SELECT AVG(pro_p) FROM EMPLOYEE ;
